### ISSUE TITLE
Scrolling with mouse or keyboard doesn't seem to exist!

### ISSUE THREAD

**Issue by thenoncoder** [tomlerendu/Quick-Tab#15]
I like this extension because it is beautiful, I love minimalism! Fix dat bug, Or else I gotta use an alternative   that is as ugly as fuck!

**Comment by thenoncoder** [comment]
Um, it looks like the dev isn't respoding to issues anymore!

**Comment by tomlerendu** [comment]
This is going to be in 4.0

**Comment by tomlerendu** [comment]
A scrollbar appears when there are lots of tabs for me (Chrome 41 on Windows). What chrome version are you using?

**Comment by thenoncoder** [comment]
I've switched back to Firefox anyways :D
