### ISSUE TITLE
Chrome 56: list shows tabs from all windows, not only the current one

### ISSUE THREAD

**Issue by ddska** [tomlerendu/Quick-Tab#29]
I'm using Quick Tab 4.2 with Chrome Version 56.0.2924.87 (64-bit) and have the following issue after recent update (not sure what exactly got upgraded):
The list started to show not only tabs from current browser window, but from all the windows of the current browser profile.
Is it the intended behavior, or it's just a bug? If it's a feature, please make it configurable.

**Comment by tomlerendu** [comment]
This is an intended feature. I will add a setting in the next version to make it configurable.

**Comment by tomlerendu** [comment]
Added in 5.0
