### ISSUE TITLE
Increase data density

### ISSUE THREAD

**Issue by zoom-mark-eastley** [tomlerendu/Quick-Tab#33]
How about reducing the white space between the entries in the drop-down list?  It would be great to see 40 or 50 entries (on a 1920 x 1080 monitor).  The search feature is great but when browsing the list, less scrolling = more efficient.

**Comment by esabol** [comment]
I agree. I would like to see a smaller font used in the menu with more items shown.

**Comment by tomlerendu** [comment]
Adding in v5
