### ISSUE TITLE
Allow up and down arrows to navigate the filtered list of tabs

### ISSUE THREAD

**Issue by matthewskelton** [tomlerendu/Quick-Tab#8]
After filtering the list of tabs, the up and down arrows should allow you to select the tab you want to switch to, and pressing Enter should switch to that tab.

**Comment by ssanj** [comment]
I really love how lightweight this plugin is. 

+1 for arrow key navigation and the Enter key to switch to the selected tab as per @matthewskelton's requirement.

**Comment by tomlerendu** [comment]
Done.
